// ==================== 数据定义 ====================
const moviesData=[{id:1,title:'星际穿越',cover:'',type:['电影'],genre:['科幻','冒险'],score:9.4,desc:'在地球面临生存危机之际，一群勇敢的探险家利用新发现的虫洞，超越人类太空旅行的极限，在广袤的宇宙中展开星际航行。',date:'2014-11-07',like:12890,collect:8560,hot:9500},{id:2,title:'鬼灭之刃',cover:'',type:['动漫'],genre:['动作','奇幻'],score:9.1,desc:'为了拯救被鬼杀死的家人，以及让变成鬼的妹妹禰豆子变回人类，炭治郎成为了鬼杀队的一员，展开了战斗。',date:'2019-04-06',like:18560,collect:12340,hot:9800},{id:3,title:'盗梦空间',cover:'',type:['电影'],genre:['科幻','悬疑'],score:9.3,desc:'道姆·柯布是一位经验老道的窃贼，他在这一行业中算得上是最厉害的，因为他能够潜入人们精神最为脆弱的梦境中，窃取潜意识中有价值的秘密。',date:'2010-09-01',like:15670,collect:9870,hot:9200},{id:4,title:'进击的巨人',cover:'',type:['动漫'],genre:['动作','悬疑'],score:9.0,desc:'为了躲避巨人的攻击而逃往内地，人类建造了三重巨大的城墙，艾伦耶格尔在亲眼目睹母亲被巨人吞噬后，立誓要消灭所有的巨人。',date:'2013-04-07',like:21340,collect:15670,hot:9900},{id:5,title:'功夫熊猫',cover:'',type:['电影'],genre:['喜剧','动作'],score:8.6,desc:'笨拙的熊猫阿宝在机缘巧合下被选为神龙大侠，与盖世五侠一起保卫和平谷，对抗邪恶的太郎。',date:'2008-06-20',like:9870,collect:6540,hot:8500},{id:6,title:'你的名字',cover:'',type:['动漫'],genre:['爱情','奇幻'],score:8.8,desc:'在日本的某个乡下小镇的高中女生三叶，每天过着忧郁的生活，而她的梦想则是能够成为东京的帅哥。',date:'2016-08-26',like:16780,collect:11230,hot:9000},{id:7,title:'千与千寻',cover:'',type:['动漫'],genre:['奇幻','冒险'],score:9.2,desc:'10岁的少女千寻与父母一起从城里搬到乡下，途中误入一个神灵的世界，她的父母因贪吃变成了猪。',date:'2001-07-20',like:23450,collect:17890,hot:9700},{id:8,title:'复仇者联盟',cover:'',type:['电影'],genre:['动作','科幻'],score:8.4,desc:'地球面临前所未有的威胁，神盾局召集了一群非凡的英雄，共同抵御邪恶势力的入侵。',date:'2012-05-04',like:14560,collect:8900,hot:8800},{id:9,title:'一拳超人',cover:'',type:['动漫'],genre:['动作','喜剧'],score:8.9,desc:'埼玉是一个拥有无敌力量的英雄，他可以一拳击败任何敌人，但也因此失去了战斗的激情。',date:'2015-10-04',like:17890,collect:12450,hot:9100},{id:10,title:'信条',cover:'',type:['电影'],genre:['科幻','悬疑'],score:8.0,desc:'主角在俄罗斯寡头萨托尔从未来得到了一种能够逆转时间的技术，企图毁灭世界。',date:'2020-09-03',like:8760,collect:5430,hot:7900},{id:11,title:'咒术回战',cover:'',genre:['动作','奇幻'],type:['动漫'],score:8.7,desc:'高中生虎杖悠仁吞下了诅咒之王两面宿傩的手指，从此卷入了咒术师的世界。',date:'2020-10-02',like:19870,collect:14560,hot:9400},{id:12,title:'疯狂动物城',cover:'',type:['电影'],genre:['喜剧','悬疑'],score:9.0,desc:'在一个所有动物和平共处的城市里，兔子警官朱迪与狐狸尼克联手调查一起神秘案件。',date:'2016-03-04',like:13450,collect:8760,hot:8600}];

// ==================== 状态管理 ====================
let state={currentFilter:'all',currentSort:'latest',searchQuery:'',likedMovies:JSON.parse(localStorage.getItem('likedMovies')||'[]'),collectedMovies:JSON.parse(localStorage.getItem('collectedMovies')||'[]'),theme:localStorage.getItem('theme')||'auto'};

// ==================== 主题管理 ====================
function initTheme(){applyTheme();setupAutoTheme();}
function applyTheme(){const theme=getEffectiveTheme();document.documentElement.setAttribute('data-theme',theme);updateThemeBtn(theme);}
function getEffectiveTheme(){if(state.theme!=='auto')return state.theme;const hour=new Date().getHours();return(hour>=6&&hour<18)?'light':'dark';}
function setupAutoTheme(){setInterval(()=>{if(state.theme==='auto')applyTheme();},60000);}
function toggleTheme(){const themes=['auto','light','dark'];const i=themes.indexOf(state.theme);state.theme=themes[(i+1)%themes.length];localStorage.setItem('theme',state.theme);applyTheme();}
function updateThemeBtn(t){const btn=document.getElementById('themeBtn');const icons={auto:'🌓',light:'☀️',dark:'🌙'};btn.textContent=icons[t];}

// ==================== AI图片生成 ====================
function generateImageUrl(prompt,ratio){const encodedPrompt=encodeURIComponent(prompt);const imageSize=ratio==='21:9'?'1792x768':'800x1000';return`https://trae-api-cn.mchost.guru/api/ide/v1/text-to-image?prompt=${encodedPrompt}&image_size=${imageSize}`;}

// ==================== 初始化图片 ====================
function initializeImages(){const bannerImg=document.getElementById('bannerImage');bannerImg.src=generateImageUrl('cinematic movie theater dark atmosphere purple neon lights film grain','21:9');bannerImg.onerror=function(){this.style.display='none'};const prompts=['interstellar movie poster epic space science fiction nasa wormhole black hole','demon slayer kimetsu no yaiba tanjiro anime poster dark fantasy','inception movie poster surreal spinning top leonardo dicaprio dream world','attack on titan anime poster eren colossal titan wall maria','kung fu panda dreamworks animation poster po dragon warrior','your name kimi no na wa anime poster makoto shinkai sky comet','spirited away studio ghibli anime poster chihiro haku bathhouse','avengers marvel superhero movie poster iron man captain america','one punch man anime poster saitama serious face','tenet movie poster christopher nolan time inversion red blue','jujutsu kaisen anime poster itadori yuji sukuna','zootopia disney animation poster judy hopps nick wilde'];moviesData.forEach((m,i)=>m.cover=generateImageUrl(prompts[i]||'movie poster','4:5'));}

// ==================== 渲染卡片 ====================
function renderCards(){const grid=document.getElementById('cardsGrid');grid.innerHTML='';let data=[...moviesData];if(state.searchQuery)data=data.filter(m=>m.title.toLowerCase().includes(state.searchQuery.toLowerCase()));if(state.currentFilter!=='all')data=data.filter(m=>m.type.includes(state.currentFilter)||m.genre.includes(state.currentFilter));switch(state.currentSort){case'latest':data.sort((a,b)=>new Date(b.date)-new Date(a.date));break;case'popular':data.sort((a,b)=>b.hot-a.hot);break;case'score':data.sort((a,b)=>b.score-a.score);break;}data.forEach((m,i)=>grid.appendChild(createCardElement(m,i)));setTimeout(observeCards,100);}

function createCardElement(movie,index){const card=document.createElement('div');card.className='card';card.style.transitionDelay=`${index*.1}s`;const isLiked=state.likedMovies.includes(movie.id);const isCollected=state.collectedMovies.includes(movie.id);const fallback='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="500" viewBox="0 0 400 500"><rect fill="#12161F" width="400" height="500"/><text x="50%" y="50%" fill="#94A3B8" font-size="60" text-anchor="middle" dominant-baseline="middle">🎬</text></svg>');card.innerHTML=`<div class="card-image-wrapper"><img class="card-image" src="${movie.cover}" alt="${movie.title}" loading="lazy"><div class="card-image-overlay"></div></div><div class="card-content"><div class="card-header"><h3 class="card-title">${movie.title}</h3><span class="card-score">⭐ ${movie.score}</span></div><div class="card-meta"><span class="card-type">${movie.type.join(' / ')}</span><span class="card-date">${movie.date}</span></div><p class="card-desc">${movie.desc}</p><div class="card-actions"><button class="action-btn ${isLiked?'liked':''}" onclick="toggleLike(${movie.id},event)">❤️ <span>${formatNumber(movie.like+(isLiked?1:0))}</span></button><button class="action-btn ${isCollected?'collected':''}" onclick="toggleCollect(${movie.id},event)">🔖 <span>${formatNumber(movie.collect+(isCollected?1:0))}</span></button></div></div>`;const img=card.querySelector('.card-image');img.onerror=function(){this.src=fallback};card.addEventListener('click',e=>{if(!e.target.closest('.action-btn'))openModal(movie);});return card;}

function formatNumber(n){return n>=10000?(n/10000).toFixed(1)+'w':n.toLocaleString();}

// ==================== 滚动动画 ====================
function observeCards(){const cards=document.querySelectorAll('.card');const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible');});},{threshold:.1});cards.forEach(c=>observer.observe(c));}

// ==================== 点赞收藏 ====================
function toggleLike(id,e){e.stopPropagation();const i=state.likedMovies.indexOf(id);i>-1?state.likedMovies.splice(i,1):state.likedMovies.push(id);localStorage.setItem('likedMovies',JSON.stringify(state.likedMovies));renderCards();}
function toggleCollect(id,e){e.stopPropagation();const i=state.collectedMovies.indexOf(id);i>-1?state.collectedMovies.splice(i,1):state.collectedMovies.push(id);localStorage.setItem('collectedMovies',JSON.stringify(state.collectedMovies));renderCards();}

// ==================== 详情弹窗 ====================
function openModal(m){const modal=document.getElementById('modalOverlay');const img=document.getElementById('modalImage');img.src=m.cover;img.onerror=function(){this.src='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="500" viewBox="0 0 400 500"><rect fill="#12161F" width="400" height="500"/><text x="50%" y="50%" fill="#94A3B8" font-size="40" text-anchor="middle" dominant-baseline="middle">🎬</text></svg>')};const isLiked=state.likedMovies.includes(m.id);const isCollected=state.collectedMovies.includes(m.id);document.getElementById('modalContent').innerHTML=`<h2 class="modal-title">${m.title}</h2><div class="modal-meta"><span class="modal-meta-item">⭐ ${m.score}分</span><span class="modal-meta-item">${m.type.join(' / ')}</span><span class="modal-meta-item">${m.genre.join(' / ')}</span><span class="modal-meta-item">${m.date}</span></div><p class="modal-description">${m.desc}</p><div class="modal-actions"><button class="modal-action-btn primary" onclick="toggleLikeInModal(${m.id})">❤️ ${isLiked?'已点赞':'点赞'} (${formatNumber(m.like+(isLiked?1:0))})</button><button class="modal-action-btn secondary" onclick="toggleCollectInModal(${m.id})">🔖 ${isCollected?'已收藏':'收藏'} (${formatNumber(m.collect+(isCollected?1:0))})</button></div>`;modal.classList.add('active');document.body.style.overflow='hidden';}
function toggleLikeInModal(id){const i=state.likedMovies.indexOf(id);i>-1?state.likedMovies.splice(i,1):state.likedMovies.push(id);localStorage.setItem('likedMovies',JSON.stringify(state.likedMovies));const movie=moviesData.find(m=>m.id===id);if(movie){openModal(movie);renderCards();}}
function toggleCollectInModal(id){const i=state.collectedMovies.indexOf(id);i>-1?state.collectedMovies.splice(i,1):state.collectedMovies.push(id);localStorage.setItem('collectedMovies',JSON.stringify(state.collectedMovies));const movie=moviesData.find(m=>m.id===id);if(movie){openModal(movie);renderCards();}}
function closeModal(){document.getElementById('modalOverlay').classList.remove('active');document.body.style.overflow='';}

// ==================== 事件监听 ====================
function setupEventListeners(){document.getElementById('searchInput').addEventListener('input',e=>{state.searchQuery=e.target.value;renderCards();});document.getElementById('filterButtons').addEventListener('click',e=>{if(e.target.classList.contains('filter-btn')){document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');state.currentFilter=e.target.dataset.filter;renderCards();}});document.getElementById('sortSelect').addEventListener('change',e=>{state.currentSort=e.target.value;renderCards();});document.getElementById('themeBtn').addEventListener('click',toggleTheme);document.getElementById('modalClose').addEventListener('click',closeModal);document.getElementById('modalOverlay').addEventListener('click',e=>{if(e.target.id==='modalOverlay')closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});}

// ==================== 初始化 ====================
function init(){initTheme();initializeImages();setupEventListeners();setTimeout(()=>{document.getElementById('loading').style.display='none';renderCards();},1000);}

// 启动
init();
